const constants = {
    address:"Address",
    clientInformation: "Client Information",
    confirm : "Confirm",
    completeCheckout: "complete checkout",
    currency: "EUR",
    deleteAllText: "Delete all",
    deleteText: "Delete",
    electronics: "Electronics",
    emailAddress: "Email Address",
    emailNoteWarning: "We'll never share your email with anyone else.",
    eur: '€',
    fleamarketAndOtherStories: "Fleamarket & other stories",
    generatedOrderId:"Generated order id:",
    goToSeeProducts: "Back to products",
    gretting: "we're glad you're here",
    home: "Home",
    item: "item",
    itemsText: "items",
    helloText: "How's it going?!",
    jewelery: "Jewelery",
    men: "Men",
    name:"Name",
    note: "we're working on something special",
    price: "Price",
    proceedToCheckout: "Proceed to checkout",
    purchaseConfirmation:"Purchase Confirmation",
    purchaseDetail:"Purchase Detail",
    qtyText: "Qty",
    seeWhatsSelling: "See what's selling",
    search: "Search",
    sold: "Sold Out",
    subtotal: "Subtotal",
    thankYouForYourPurchase: "Thank you for your purchase",
    total: "Total",
    units: "units",
    warningNote: "It seems that you have no products to complete the purchase, you should take a look at our products",
    welcome: "welcome!",
    women: "Women", 
}
 
export default constants