const constants = {
    confirm : "Confirm",
    confirmOrderText: "Proceed to checkout",
    currency: "EUR",
    deleteAllText: "Delete all",
    deleteText: "Delete",
    electronics: "Electronics",
    eur: '€',
    fleamarketAndOtherStories: "Fleamarket & other stories",
    goToSeeProducts: "Back to products",
    gretting: "we're glad you're here",
    home: "Home",
    item: "item",
    itemsText: "items",
    jewelery: "Jewelery",
    men: "Men",
    note: "we're working on something special",
    price: "Price",
    proceedToCheckout: "Proceed to checkout",
    qtyText: "Qty",
    seeWhatsSelling: "See what's selling",
    search: "Search",
    subtotal: "Subtotal",
    total: "Total",
    welcome: "welcome!",
    women: "Women", 
}
 
export default constants